// ===== CHECKLIST DATA =====
const CHECKLIST = [
  // Phase 1
  // DOG (Nala) — staying with UK family 6-9 months, target travel-ready ~Jan 2027
  // 180-day wait starts from date LAB RECEIVES blood sample, not draw date
  {id:'c1_1',text:'Confirm PetAir UK as relocation company (01725 551124 / petairuk.com)',phase:1,week:1,cost:'Free',cat:'Dog'},
  {id:'c1_2',text:'Confirm microchip registered owner = person importing to AU (update if needed)',phase:1,week:1,cost:'Free',cat:'Dog'},
  {id:'c1_3',text:'Check Nala has NOT been vaccinated against Leishmania (CaniLeish) — positive test = barred from AU',phase:1,week:1,cost:'Free',cat:'Dog'},
  {id:'c1_4',text:'Confirm rabies vaccination is current (3-year vaccine OK). Get vaccinated if not — must be valid at blood test AND export',phase:1,week:2,cost:'£50–£80',cat:'Dog'},
  {id:'c1_5',text:'1st ID check — must be OV66 authorised vet. PetAir Windsor branch available (£120)',phase:1,week:3,cost:'£120',cat:'Dog'},
  {id:'c1_6',text:'2nd ID check — DIFFERENT vet practice, also OV66 authorised. Must be before blood sample',phase:1,week:4,cost:'£80–£120',cat:'Dog'},
  {id:'c1_7',text:'Rabies blood sample (RNATT) — can be same appointment as 2nd ID check but NOT before it. 180-day wait starts when LAB RECEIVES sample',phase:2,week:5,cost:'£100–£200',cat:'Dog'},
  {id:'c1_8',text:'Confirm blood sample received by testing lab — note the DATE (this starts the 180-day clock)',phase:2,week:5,cost:'Free',cat:'Dog'},
  {id:'c1_9',text:'Begin crate training (daily 15-30 min sessions)',phase:2,week:6,cost:'£50–£150',cat:'Dog'},
  {id:'c1_10',text:'Apply for Australian import permit (PetAir handles)',phase:2,week:8,cost:'Included',cat:'Dog'},
  {id:'c1_11',text:'Confirm family member caring for Nala in UK — handover plan',phase:3,week:10,cost:'Free',cat:'Dog'},
  {id:'c1_12',text:'180-day wait checkpoint — confirm date Nala is eligible to fly',phase:3,week:12,cost:'Free',cat:'Dog'},
  {id:'c1_13',text:'Book Nala flight + quarantine (10 days Mickleham if both ID checks done, otherwise 30 days)',phase:3,week:12,cost:'£3k–£6k',cat:'Dog'},
  {id:'c1_14',text:'Pre-export vet visits (3 visits in weeks before flight — PetAir will schedule exact dates)',phase:4,week:14,cost:'Included/£200–£400',cat:'Dog'},
  {id:'c1_15',text:'Veterinary Health Certificate (VHC) endorsement — must be DIFFERENT vet from blood sample vet',phase:4,week:14,cost:'Included',cat:'Dog'},
  {id:'c2_1',text:'Contact 3 letting agents',phase:1,week:1,cost:'Free',cat:'Property'},
  {id:'c2_2',text:'Get rental valuations',phase:1,week:2,cost:'Free',cat:'Property'},
  {id:'c2_3',text:'Apply for Consent to Let from lender',phase:1,week:2,cost:'£0–£100',cat:'Property'},
  {id:'c2_4',text:'Switch to landlord insurance',phase:1,week:3,cost:'£200–£400/yr',cat:'Property'},
  {id:'c2_5',text:'Decide: fully managed vs let-only',phase:1,week:2,cost:'—',cat:'Property'},
  {id:'c2_6',text:'Instruct chosen agent',phase:1,week:4,cost:'—',cat:'Property'},
  {id:'c2_7',text:'Register for NRL Scheme (HMRC)',phase:1,week:4,cost:'Free',cat:'Property'},
  {id:'c3_1',text:'Walk through every room — categorise items',phase:1,week:1,cost:'Free',cat:'Declutter'},
  {id:'c3_2',text:'List items >£200 on Marketplace/eBay',phase:1,week:2,cost:'Free',cat:'Declutter'},
  {id:'c3_3',text:'Book charity collection',phase:1,week:2,cost:'Free',cat:'Declutter'},
  {id:'c3_4',text:'Book skip or council bulk waste',phase:1,week:2,cost:'£150–£300',cat:'Declutter'},
  {id:'c3_5',text:'Remove 50–70% of household contents',phase:1,week:4,cost:'—',cat:'Declutter'},
  {id:'c4_1',text:'Get 3 shipping quotes',phase:1,week:3,cost:'Free',cat:'Shipping'},
  {id:'c4_2',text:'Decide: groupage vs dedicated',phase:1,week:3,cost:'—',cat:'Shipping'},
  {id:'c4_3',text:'Create shipping inventory list',phase:1,week:4,cost:'Free',cat:'Shipping'},
  {id:'c5_1',text:'Open Wise account',phase:1,week:1,cost:'Free',cat:'Financial'},
  {id:'c5_2',text:'Open Revolut account',phase:1,week:1,cost:'Free',cat:'Financial'},
  {id:'c5_3',text:'Set up GBP→AUD rate alerts',phase:1,week:1,cost:'Free',cat:'Financial'},
  {id:'c5_4',text:'Review all UK direct debits',phase:1,week:2,cost:'Free',cat:'Financial'},
  {id:'c5_5',text:'Convert first tranche £15k–£20k → AUD',phase:1,week:3,cost:'£300–£600',cat:'Financial'},
  {id:'c5_6',text:'Notify UK bank of overseas move',phase:1,week:4,cost:'Free',cat:'Financial'},
  {id:'c5_7',text:'Pre-open AU bank account (CommBank)',phase:1,week:4,cost:'Free',cat:'Financial'},
  {id:'ch_1',text:'Book dental checkups — whole family (NHS)',phase:1,week:2,cost:'Free',cat:'Health'},
  {id:'ch_2',text:'Book GP appointments — prescriptions',phase:1,week:2,cost:'Free',cat:'Health'},
  {id:'ch_3',text:'Book eye tests',phase:1,week:3,cost:'Free/£25',cat:'Health'},
  {id:'ch_4',text:'Get kids immunisation records',phase:1,week:3,cost:'Free',cat:'Health'},
  {id:'ch_5',text:'Request full medical summaries from GP',phase:1,week:4,cost:'Free',cat:'Health'},
  {id:'ch_6',text:'Stock up on regular medications',phase:1,week:4,cost:'NHS cost',cat:'Health'},
  {id:'cp_1',text:'Check UK State Pension NI record',phase:1,week:3,cost:'Free',cat:'Pension'},
  {id:'cp_2',text:'Decide: voluntary NI contributions from AU',phase:1,week:4,cost:'~£800/yr',cat:'Pension'},
  {id:'cp_3',text:'Locate all UK workplace pensions',phase:1,week:3,cost:'Free',cat:'Pension'},
  // Phase 2
  {id:'c6_1',text:'Gas Safety Certificate (CP12)',phase:2,week:5,cost:'£60–£90',cat:'Property'},
  {id:'c6_2',text:'EICR electrical cert',phase:2,week:5,cost:'£120–£250',cat:'Property'},
  {id:'c6_3',text:'EPC certificate',phase:2,week:5,cost:'£60–£120',cat:'Property'},
  {id:'c6_4',text:'Smoke alarms & CO detectors',phase:2,week:5,cost:'£30–£80',cat:'Property'},
  {id:'c6_5',text:'Fix all defects',phase:2,week:6,cost:'£200–£1,000',cat:'Property'},
  {id:'c6_6',text:'Paint touch-up',phase:2,week:6,cost:'£50–£200',cat:'Property'},
  {id:'c6_7',text:'Professional deep clean',phase:2,week:7,cost:'£150–£300',cat:'Property'},
  {id:'c6_8',text:'Professional photos',phase:2,week:7,cost:'£100–£200',cat:'Property'},
  {id:'c6_9',text:'List property with agent',phase:2,week:8,cost:'—',cat:'Property'},

  // Landlord checklist - additional items
  {id:'c6_11',text:'Provide ID and proof of ownership to agent',phase:2,week:5,cost:'Free',cat:'Property'},
  {id:'c6_12',text:'Check if local letting licence required (check with council)',phase:2,week:5,cost:'Free',cat:'Property'},
  {id:'c6_13',text:'PAT test all portable appliances left in property',phase:2,week:6,cost:'£50–£150',cat:'Property'},
  {id:'c6_14',text:'Legionella risk assessment (water systems)',phase:2,week:6,cost:'£50–£100',cat:'Property'},
  {id:'c6_15',text:'Check all furniture is fire-safety compliant and labelled',phase:2,week:6,cost:'Free',cat:'Property'},
  {id:'c6_16',text:'Professional inventory & schedule of condition',phase:2,week:7,cost:'£100–£200',cat:'Property'},
  {id:'c6_17',text:'Set up secure rent payment method',phase:2,week:8,cost:'Free',cat:'Property'},
  {id:'c6_18',text:'Right to Rent check on tenant (agent handles)',phase:2,week:8,cost:'Free',cat:'Property'},
  {id:'c6_19',text:'Provide tenant: How to Rent guide, Gas cert, EPC, EICR copies',phase:2,week:8,cost:'Free',cat:'Property'},
  {id:'c6_20',text:'Consider rent protection insurance',phase:2,week:7,cost:'£150–£300/yr',cat:'Property'},
  {id:'c6_21',text:'Consider home emergency cover',phase:2,week:7,cost:'£100–£200/yr',cat:'Property'},
  {id:'c6_22',text:'Consider legal expense cover',phase:2,week:7,cost:'£50–£100/yr',cat:'Property'},
  {id:'c7_1',text:'Get car valuations',phase:2,week:5,cost:'Free',cat:'Cars'},
  {id:'c7_2',text:'List car for sale',phase:2,week:6,cost:'£0–£30',cat:'Cars'},
  {id:'c7_3',text:'Sell car — accept reasonable offer',phase:2,week:7,cost:'—',cat:'Cars'},
  {id:'c7_4',text:'Cancel car insurance after sale',phase:2,week:8,cost:'—',cat:'Cars'},
  {id:'c8_1',text:'Lock in shipping company & date',phase:2,week:6,cost:'Deposit £200–£500',cat:'Shipping'},
  {id:'c8_2',text:'Schedule collection Week 9–10',phase:2,week:6,cost:'—',cat:'Shipping'},
  {id:'c9_1',text:'Give notice on broadband',phase:2,week:5,cost:'—',cat:'Contracts'},
  {id:'c9_2',text:'Cancel TV licence',phase:2,week:8,cost:'—',cat:'Contracts'},
  {id:'c9_3',text:'Cancel gym memberships',phase:2,week:5,cost:'—',cat:'Contracts'},
  {id:'c9_4',text:'Cancel streaming services',phase:2,week:8,cost:'—',cat:'Contracts'},
  {id:'c9_5',text:'Review & cancel all subscriptions',phase:2,week:6,cost:'—',cat:'Contracts'},
  {id:'c9_6',text:'Royal Mail redirect',phase:2,week:8,cost:'£60–£100',cat:'Contracts'},
  {id:'c10_1',text:'Research AU health cover (OVHC)',phase:2,week:6,cost:'—',cat:'Insurance'},
  {id:'c10_2',text:'Compare family plans — 3 quotes',phase:2,week:6,cost:'—',cat:'Insurance'},
  {id:'c10_3',text:'Set up policy for arrival date',phase:2,week:8,cost:'$300–$500/mo',cat:'Insurance'},
  {id:'c11_1',text:'Confirm flight details with company',phase:2,week:7,cost:'Company',cat:'Flights'},
  {id:'c11_2',text:'Confirm baggage allowances',phase:2,week:8,cost:'—',cat:'Flights'},
  {id:'c11_3',text:'Request stopover for kids',phase:2,week:7,cost:'—',cat:'Flights'},
  {id:'cv_1',text:'Register as overseas voter (UK)',phase:2,week:7,cost:'Free',cat:'Admin'},
  {id:'cps_1',text:'Partner: update CV for AU format',phase:2,week:6,cost:'Free',cat:'Partner'},
  {id:'cps_2',text:'Partner: research AU job market',phase:2,week:6,cost:'Free',cat:'Partner'},
  {id:'cw_1',text:'Review UK wills',phase:2,week:7,cost:'Free',cat:'Legal'},
  {id:'cw_2',text:'Consider UK Power of Attorney',phase:2,week:7,cost:'£100–£300',cat:'Legal'},
  // Phase 3
  {id:'c12_1',text:'Supervised packing with movers',phase:3,week:10,cost:'Included',cat:'Shipping'},
  {id:'c12_2',text:'Photograph all items before boxing',phase:3,week:10,cost:'Free',cat:'Shipping'},
  {id:'c12_3',text:'Keep essentials separate',phase:3,week:10,cost:'—',cat:'Shipping'},
  {id:'c13_1',text:'Chase agent for tenant applications',phase:3,week:10,cost:'—',cat:'Property'},
  {id:'c13_2',text:'Review & approve tenant references',phase:3,week:11,cost:'—',cat:'Property'},
  {id:'c13_3',text:'Sign tenancy agreement',phase:3,week:12,cost:'—',cat:'Property'},
  {id:'c14_1',text:'Final meter readings',phase:3,week:12,cost:'Free',cat:'UK Exit'},
  {id:'c14_2',text:'Cancel/transfer utilities',phase:3,week:12,cost:'Free',cat:'UK Exit'},
  {id:'c14_3',text:'Submit P85 to HMRC',phase:3,week:12,cost:'Free',cat:'UK Exit'},
  {id:'c14_4',text:'Get medical records (all family)',phase:3,week:10,cost:'Free',cat:'UK Exit'},
  {id:'c14_5',text:'Get dental records/x-rays',phase:3,week:10,cost:'Free',cat:'UK Exit'},
  {id:'c14_6',text:'Get kids school records',phase:3,week:11,cost:'Free',cat:'UK Exit'},
  {id:'c14_7',text:'Request car insurer no-claims letter',phase:3,week:11,cost:'Free',cat:'UK Exit'},
  {id:'ck_1',text:'Organise farewell gatherings for kids',phase:3,week:11,cost:'£50–£100',cat:'Kids'},
  {id:'ck_2',text:'Get contact details for kids friends',phase:3,week:11,cost:'Free',cat:'Kids'},
  {id:'ck_3',text:'Download offline entertainment for flight',phase:3,week:12,cost:'£20–£50',cat:'Kids'},
  {id:'c15_1',text:'Pack 6–8 weeks clothing (all 4)',phase:3,week:12,cost:'—',cat:'Packing'},
  {id:'c15_2',text:'Pack work setup',phase:3,week:12,cost:'—',cat:'Packing'},
  {id:'c15_3',text:'Prepare documents folder (carry-on)',phase:3,week:11,cost:'—',cat:'Packing'},
  {id:'c15_4',text:'Buy AU power adapters',phase:3,week:10,cost:'£10–£20',cat:'Packing'},
  {id:'c15_5',text:'Scan all documents to cloud',phase:3,week:11,cost:'Free',cat:'Packing'},
  // Phase 4
  {id:'c16_1',text:'Verify AU bank account in-branch',phase:4,week:13,cost:'Free',cat:'AU Admin'},
  {id:'c16_2',text:'Apply for TFN (both adults)',phase:4,week:13,cost:'Free',cat:'AU Admin'},
  {id:'c16_3',text:'Activate AU health insurance',phase:4,week:13,cost:'—',cat:'AU Admin'},
  {id:'c16_4',text:'Get AU SIM cards (all family)',phase:4,week:13,cost:'$40–$120',cat:'AU Admin'},
  {id:'c16_5',text:'Register with Medicare',phase:4,week:13,cost:'Free',cat:'AU Admin'},
  {id:'c16_6',text:'Register with local GP',phase:4,week:13,cost:'Free',cat:'AU Admin'},
  {id:'c17_1',text:'Set up Domain/Realestate alerts',phase:4,week:13,cost:'Free',cat:'AU Housing'},
  {id:'c17_2',text:'Attend rental inspections daily',phase:4,week:14,cost:'Free',cat:'AU Housing'},
  {id:'c17_3',text:'Secure rental — pay bond + advance',phase:4,week:15,cost:'$3,500–$5,000',cat:'AU Housing'},
  {id:'c18_1',text:'Contact target schools',phase:4,week:13,cost:'Free',cat:'AU School'},
  {id:'c18_2',text:'Submit enrolment forms',phase:4,week:14,cost:'—',cat:'AU School'},
  {id:'c18_3',text:'Pay school fees',phase:4,week:14,cost:'$5k–$10k/yr each',cat:'AU School'},
  {id:'c18_4',text:'Buy school uniforms',phase:4,week:15,cost:'$200–$400 each',cat:'AU School'},
  {id:'c19_1',text:'Research cars on Carsales.com.au',phase:4,week:14,cost:'Free',cat:'AU Car'},
  {id:'c19_2',text:'Get RACV inspection',phase:4,week:15,cost:'$200–$350',cat:'AU Car'},
  {id:'c19_3',text:'Buy car',phase:4,week:15,cost:'$15k–$20k',cat:'AU Car'},
  {id:'c19_4',text:'Get car insurance',phase:4,week:15,cost:'$100–$200/mo',cat:'AU Car'},
  {id:'c20_1',text:'Set up electricity + gas',phase:4,week:15,cost:'Free',cat:'AU Setup'},
  {id:'c20_2',text:'Set up internet (NBN)',phase:4,week:15,cost:'$70–$90/mo',cat:'AU Setup'},
  {id:'cdr_1',text:'Set up CityLink + EastLink toll accounts',phase:4,week:15,cost:'Free',cat:'AU Driving'},
  {id:'cdr_2',text:'Learn hook turns and tram rules',phase:4,week:13,cost:'Free',cat:'AU Driving'},
  {id:'cpa_1',text:'Partner: register on Seek/LinkedIn',phase:4,week:14,cost:'Free',cat:'Partner'},
  {id:'cpa_2',text:'Partner: join local community groups',phase:4,week:14,cost:'Free',cat:'Partner'},
  {id:'cka_1',text:'Enrol kids in local sport/activity',phase:4,week:15,cost:'$50–$200',cat:'Kids'},
  {id:'cka_2',text:'Set up video call schedule with UK friends',phase:4,week:14,cost:'Free',cat:'Kids'},
  {id:'csa_1',text:'Track shipment arrival',phase:4,week:20,cost:'Free',cat:'Shipping'},
  {id:'csa_2',text:'Unpack & check against inventory',phase:4,week:21,cost:'Free',cat:'Shipping'},
  {id:'csa_3',text:'File insurance claim if damage (within 14 days)',phase:4,week:21,cost:'Free',cat:'Shipping'},
];
